module.exports = {
	frontSide: [
	"Who was the 1st president of the United States?",
	"Who was the 2nd president of the United States?",
	"Who was the 3rd president of the United States?",
	"Who was the 4th president of the United States?",
	"Who was the 5th president of the United States?",
	"Who was the 6th president of the United States?",
	"Who was the 7th president of the United States?",
	"Who was the 8th president of the United States?",
	"Who was the 9th president of the United States?",
	"Who was the 10th president of the United States?",
	"Who was the 11th president of the United States?",
	"Who was the 12th president of the United States?",
	"Who was the 13th president of the United States?",
	"Who was the 14th president of the United States?",
	"Who was the 15th president of the United States?",
	"Who was the 16th president of the United States?",
	"Who was the 17th president of the United States?",
	"Who was the 18th president of the United States?",
	"Who was the 19th president of the United States?",
	"Who was the 20th president of the United States?",
	"Who was the 21st president of the United States?",
	"Who was the 22nd president of the United States?",
	"Who was the 23rd president of the United States?",
	"Who was the 24th president of the United States?",
	"Who was the 25th president of the United States?",
	"Who was the 26th president of the United States?",
	"Who was the 27th president of the United States?",
	"Who was the 28th president of the United States?",
	"Who was the 29th president of the United States?",
	"Who was the 30th president of the United States?",
	"Who was the 31st president of the United States?",
	"Who was the 32nd president of the United States?",
	"Who was the 33rd president of the United States?",
	"Who was the 34th president of the United States?",
	"Who was the 35th president of the United States?",
	"Who was the 36th president of the United States?",
	"Who was the 37th president of the United States?",
	"Who was the 38th president of the United States?",
	"Who was the 39th president of the United States?",
	"Who was the 40th president of the United States?",
	"Who was the 41st president of the United States?",
	"Who was the 42nd president of the United States?",
	"Who was the 43rd president of the United States?",
	"Who was the 44th president of the United States?",
	"Who was the 45th president of the United States?"],
	backSide: [
	"George Washington",
	"John Adams",
	"Thomas Jefferson",
	"James Madison",
	"James Monroe",
	"John Quincy Adams",
	"Andrew Jackson",
	"Martin Van Buren",
	"William Henry Harrison",
	"John Tyler",
	"James K. Polk",
	"Zachary Taylor",
	"Millard Fillmore",
	"Franklin Pierce",
	"James Buchanan",
	"Abraham Lincoln",
	"Andrew Johnson",
	"Ulysses S. Grant",
	"Rutherford B. Hayes",
	"James A. Garfield",
	"Chester Arthur",
	"Grover Cleveland",
	"Benjamin Harrison",
	"Grover Cleveland",
	"William McKinley",
	"Theodore Roosevelt",
	"William Taft",
	"Woodrow Wilson",
	"Warren Harding",
	"Calvin Coolidge",
	"Herbert Hoover",
	"Franklin Roosevelt",
	"Harry Truman",
	"Dwight Eisenhower",
	"John F. Kennedy",
	"Lyndon Johnson",
	"Richard Nixon",
	"Gerald Ford",
	"Jimmy Carter",
	"Ronald Reagan",
	"George H. W. Bush",
	"Bill Clinton",
	"George W. Bush",
	"Barack Obama",
	"Donald J. Trump"]
}