module.exports = {
	partial: [
	"...was the 1st president of the United States.",
	"...was the 2nd president of the United States.",
	"...was the 3rd president of the United States.",
	"...was the 4th president of the United States.",
	"...was the 5th president of the United States.",
	"...was the 6th president of the United States.",
	"...was the 7th president of the United States.",
	"...was the 8th president of the United States.",
	"...was the 9th president of the United States.",
	"...was the 10th president of the United States.",
	"...was the 11th president of the United States.",
	"...was the 12th president of the United States.",
	"...was the 13th president of the United States.",
	"...was the 14th president of the United States.",
	"...was the 15th president of the United States.",
	"...was the 16th president of the United States.",
	"...was the 17th president of the United States.",
	"...was the 18th president of the United States.",
	"...was the 19th president of the United States.",
	"...was the 20th president of the United States.",
	"...was the 21st president of the United States.",
	"...was the 22nd president of the United States.",
	"...was the 23rd president of the United States.",
	"...was the 24th president of the United States.",
	"...was the 25th president of the United States.",
	"...was the 26th president of the United States.",
	"...was the 27th president of the United States.",
	"...was the 28th president of the United States.",
	"...was the 29th president of the United States.",
	"...was the 30th president of the United States.",
	"...was the 31st president of the United States.",
	"...was the 32nd president of the United States.",
	"...was the 33rd president of the United States.",
	"...was the 34th president of the United States.",
	"...was the 35th president of the United States.",
	"...was the 36th president of the United States.",
	"...was the 37th president of the United States.",
	"...was the 38th president of the United States.",
	"...was the 39th president of the United States.",
	"…...was the 40th president of the United States.",
	"...was the 41st president of the United States.",
	"...was the 42nd president of the United States.",
	"...was the 43rd president of the United States.",
	"...was the 44th president of the United States.",
	"...was the 45th president of the United States."],
	complete: [
	"George Washington was the 1st president of the United States.",
	"John Adams was the 2nd president of the United States.",
	"Thomas Jefferson was the 3rd president of the United States.",
	"James Madison was the 4th president of the United States.",
	"James Monroe was the 5th president of the United States.",
	"John Quincy Adams was the 6th president of the United States.",
	"Andrew Jackson was the 7th president of the United States.",
	"Martin Van Buren was the 8th president of the United States.",
	"William Henry Harrison was the 9th president of the United States.",
	"John Tyler was the 10th president of the United States.",
	"James K. Polk was the 11th president of the United States.",
	"Zachary Taylor was the 12th president of the United States.",
	"Millard Fillmore was the 13th president of the United States.",
	"Franklin Pierce was the 14th president of the United States.",
	"James Buchanan was the 15th president of the United States.",
	"Abraham Lincoln was the 16th president of the United States.",
	"Andrew Johnson was the 17th president of the United States.",
	"Ulysses S. Grant was the 18th president of the United States.",
	"Rutherford B. Hayes was the 19th president of the United States.",
	"James A. Garfield was the 20th president of the United States.",
	"Chester Arthur was the 21st president of the United States.",
	"Grover Cleveland was the 22nd president of the United States.",
	"Benjamin Harrison was the 23rd president of the United States.",
	"Grover Cleveland was the 24th president of the United States.",
	"William McKinley was the 25th president of the United States.",
	"Theodore Roosevelt was the 26th president of the United States.",
	"William Taft was the 27th president of the United States.",
	"Woodrow Wilson was the 28th president of the United States.",
	"Warren Harding was the 29th president of the United States.",
	"Calvin Coolidge was the 30th president of the United States.",
	"Herbert Hoover was the 31st president of the United States.",
	"Franklin Roosevelt was the 32nd president of the United States.",
	"Harry Truman was the 33rd president of the United States.",
	"Dwight Eisenhower was the 34th president of the United States.",
	"John F. Kennedy was the 35th president of the United States.",
	"Lyndon Johnson was the 36th president of the United States.",
	"Richard Nixon was the 37th president of the United States.",
	"Gerald Ford was the 38th president of the United States.",
	"Jimmy Carter was the 39th president of the United States.",
	"Ronald Reagan was the 40th president of the United States.",
	"George H. W. Bush was the 41st president of the United States.",
	"Bill Clinton was the 42nd president of the United States.",
	"George W. Bush was the 43rd president of the United States.",
	"Barack Obama was the 44th president of the United States.",
	"Donald J. Trump was the 45th president of the United States."]
}